/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_admin_rules_get"];
        put?: never;
        /**
         * Create Draft
         * @description Crea una nueva versión de regla en estado draft.
         *
         *     `version` se autoincrementa: max(version) + 1 para (domain, key)
         *     o 1 si no existía.
         */
        post: operations["create_draft_api_admin_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rules/validate-schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Schema
         * @description Valida `rules` contra el JSON Schema del dominio. No persiste.
         */
        post: operations["validate_schema_api_admin_rules_validate_schema_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rule */
        get: operations["get_rule_api_admin_rules__rule_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rules/{rule_id}/deprecate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deprecate Rule */
        post: operations["deprecate_rule_api_admin_rules__rule_id__deprecate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rules/{rule_id}/dry-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dry Run
         * @description Evalúa la regla nueva sobre los inputs persistidos en
         *     `core.recomendaciones` y reporta cuántas cambiarían su veredicto.
         *
         *     Solo aplica al dominio `regime_eligibility`; otros dominios
         *     devuelven 422 con explicación. El motor recorre cada
         *     recomendación de tipo `cambio_regimen` cuyo régimen recomendado
         *     coincide con la `key` de la regla, y compara `pasaba_antes` (lo
         *     que registra el outputs.elegibilidad) contra `pasa_ahora`
         *     (resultado del evaluator con la regla nueva).
         */
        post: operations["dry_run_api_admin_rules__rule_id__dry_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rules/{rule_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Rule
         * @description Segunda firma → published.
         *
         *     El constraint de la tabla exige published_by_contador !=
         *     published_by_admin; si el mismo usuario firmó ambos, Postgres
         *     rechaza con check_violation y devolvemos 409.
         */
        post: operations["publish_rule_api_admin_rules__rule_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rules/{rule_id}/sign-contador": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign Contador
         * @description Primera firma → pending_approval. published_by_contador queda
         *     seteado y el segundo firmante (admin técnico, distinto) ejecuta
         *     /publish para activar la regla.
         */
        post: operations["sign_contador_api_admin_rules__rule_id__sign_contador_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alertas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alertas
         * @description Lista alertas del workspace activo (RLS filtra). Por defecto solo
         *     abiertas (`nueva` y `vista`).
         */
        get: operations["list_alertas_api_alertas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alertas/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate Alertas
         * @description Evalúa el estado declarado y persiste las alertas nuevas.
         *
         *     Dedup por (workspace_id, empresa_id, tax_year, tipo) sobre alertas
         *     abiertas (estado in nueva|vista). Si el usuario descartó la alerta
         *     antes, vuelve a aparecer en la próxima evaluación si la condición
         *     persiste.
         */
        post: operations["evaluate_alertas_api_alertas_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alertas/{alerta_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Alerta
         * @description Cambia el estado de una alerta (vista | descartada | accionada).
         */
        patch: operations["update_alerta_api_alertas__alerta_id__patch"];
        trace?: never;
    };
    "/api/calc/comparador-regimen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Comparador Regimen */
        post: operations["comparador_regimen_api_calc_comparador_regimen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calc/idpc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calc Idpc */
        post: operations["calc_idpc_api_calc_idpc_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calc/igc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calc Igc */
        post: operations["calc_igc_api_calc_igc_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calc/ppm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calc Ppm */
        post: operations["calc_ppm_api_calc_ppm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cartera": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cartera
         * @description Devuelve la cartera enriquecida del workspace activo.
         */
        get: operations["get_cartera_api_cartera_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/empresas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Empresas
         * @description Lista empresas visibles bajo RLS, ordenadas por created_at desc.
         */
        get: operations["list_empresas_api_empresas_get"];
        put?: never;
        /** Create Empresa */
        post: operations["create_empresa_api_empresas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/legal/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Legal */
        get: operations["get_legal_api_legal__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/privacy/arcop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Arcop
         * @description Lista solicitudes del titular. Admins (owner / accountant_lead)
         *     ven todas las del workspace activo.
         *
         *     `tenant_session` del backend corre como postgres (superuser) y
         *     bypassa RLS, por eso filtramos explícito por workspace_id +
         *     user_id según rol — defensa en profundidad.
         */
        get: operations["list_arcop_api_privacy_arcop_get"];
        put?: never;
        /**
         * Create Arcop
         * @description Recibe una solicitud ARCOP. Estado inicial = 'recibida'.
         *
         *     Gatilla audit_log con `action='create'` y `resource_type='arcop'` para
         *     cumplir el principio de trazabilidad de la Ley 21.719.
         */
        post: operations["create_arcop_api_privacy_arcop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/privacy/arcop/{arcop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Arcop
         * @description PATCH para el DPO: avanza estado y registra respuesta.
         *
         *     Solo `owner` y `accountant_lead` pueden gestionar. Pasar a estado
         *     terminal (cumplida / rechazada) setea `respondida_at = now()`. Si
         *     ya está terminal, rechazar el PATCH.
         */
        patch: operations["update_arcop_api_privacy_arcop__arcop_id__patch"];
        trace?: never;
    };
    "/api/public/legal/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Legal Public
         * @description Versión pública del lookup legal — sin auth.
         *
         *     Los textos legales son por definición públicos (T&C, privacidad).
         *     Usamos `service_session` para no necesitar un JWT y respondemos
         *     el mismo shape que `/api/legal/{key}`.
         */
        get: operations["get_legal_public_api_public_legal__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regime/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Diagnose */
        post: operations["diagnose_api_regime_diagnose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regime/recomendaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recomendaciones
         * @description Lista recomendaciones del workspace activo (RLS filtra).
         */
        get: operations["list_recomendaciones_api_regime_recomendaciones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenario/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare
         * @description Compara hasta 4 escenarios lado a lado y consolida plan de acción.
         *
         *     `es_recomendado` se asigna al escenario con menor carga total entre
         *     los provistos (lícitos por construcción, ya validados al simular).
         *     Empate → menos palancas activadas.
         */
        post: operations["compare_api_scenario_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenario/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scenarios
         * @description Lista escenarios del workspace activo (RLS filtra automáticamente).
         *
         *     `es_recomendado` se calcula en vivo: el escenario con menor carga
         *     total entre los listados queda marcado. Empate → desempata por
         *     menor cantidad de palancas activadas (preferencia por simplicidad).
         */
        get: operations["list_scenarios_api_scenario_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenario/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_api_scenario_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Workspace
         * @description Crea workspace + miembro inicial + consentimiento + audit log.
         *
         *     Atómico: si cualquier paso falla, todo se revierte. El usuario debe
         *     refrescar su sesión Supabase tras este POST para que el Auth Hook
         *     re-ejecute y inyecte la tenancy en el JWT.
         */
        post: operations["create_workspace_api_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertaResponse */
        AlertaResponse: {
            /** Accion Recomendada */
            accion_recomendada: string | null;
            /** Created At */
            created_at: string;
            /** Descripcion */
            descripcion: string;
            /** Empresa Id */
            empresa_id: string | null;
            /**
             * Estado
             * @enum {string}
             */
            estado: "nueva" | "vista" | "descartada" | "accionada";
            /** Fecha Limite */
            fecha_limite: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Severidad
             * @enum {string}
             */
            severidad: "info" | "warning" | "critical";
            /** Tipo */
            tipo: string;
            /** Titulo */
            titulo: string;
        };
        /** AlertasListResponse */
        AlertasListResponse: {
            /** Alertas */
            alertas: components["schemas"]["AlertaResponse"][];
        };
        /** ArcopListResponse */
        ArcopListResponse: {
            /** Solicitudes */
            solicitudes: components["schemas"]["ArcopResponse"][];
        };
        /** ArcopResponse */
        ArcopResponse: {
            /** Descripcion */
            descripcion: string | null;
            /**
             * Estado
             * @enum {string}
             */
            estado: "recibida" | "en_proceso" | "cumplida" | "rechazada";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Recibida At */
            recibida_at: string;
            /** Respondida At */
            respondida_at: string | null;
            /** Respuesta */
            respuesta: string | null;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "acceso" | "rectificacion" | "cancelacion" | "oposicion" | "portabilidad";
        };
        /** BanderaRoja */
        BanderaRoja: {
            /** Mensaje */
            mensaje: string;
            /** Palanca Id */
            palanca_id: string;
            /**
             * Severidad
             * @enum {string}
             */
            severidad: "warning" | "block";
        };
        /** CalculationResponse */
        CalculationResponse: {
            /**
             * Currency
             * @default CLP
             * @constant
             */
            currency: "CLP";
            /**
             * Disclaimer
             * @default 🟡 Resultado calculado con parámetros tributarios PLACEHOLDER pendientes de validación por contador socio. NO usar para decisiones tributarias reales hasta que se publique la versión firmada.
             */
            disclaimer: string;
            /** Fuente Legal */
            fuente_legal: string;
            /** Tax Year */
            tax_year: number;
            /** Value */
            value: string;
        };
        /** CarteraEmpresaItem */
        CarteraEmpresaItem: {
            /** Alertas Abiertas */
            alertas_abiertas: number;
            /**
             * Empresa Id
             * Format: uuid
             */
            empresa_id: string;
            /** Razon Social */
            razon_social: string;
            /**
             * Regimen Actual
             * @enum {string}
             */
            regimen_actual: "14_a" | "14_d_3" | "14_d_8" | "presunta" | "desconocido";
            /** Rut */
            rut: string;
            /** Score Oportunidad */
            score_oportunidad: number;
            ultima_recomendacion: components["schemas"]["UltimaRecomendacion"] | null;
            ultima_simulacion: components["schemas"]["UltimaSimulacion"] | null;
        };
        /** CarteraResponse */
        CarteraResponse: {
            /** Ahorro Potencial Estimado Clp */
            ahorro_potencial_estimado_clp: string;
            /** Empresas */
            empresas: components["schemas"]["CarteraEmpresaItem"][];
            /** Total Alertas Abiertas */
            total_alertas_abiertas: number;
            /** Total Empresas */
            total_empresas: number;
        };
        /** ComparadorRequest */
        ComparadorRequest: {
            /**
             * Retiros Pesos
             * @description Retiros del dueño en el año, CLP
             */
            retiros_pesos: number | string;
            /**
             * Rli
             * @description RLI proyectada en CLP
             */
            rli: number | string;
            /** Tax Year */
            tax_year: number;
        };
        /** ComparadorResponse */
        ComparadorResponse: {
            /**
             * Disclaimer
             * @default 🟡 Comparativa calculada con parámetros tributarios PLACEHOLDER pendientes de validación por contador socio. Esta versión NO considera registros SAC/RAI/REX, créditos imputados ni proyección multi-año (eso entra en fase 3 oficial). NO usar para decisiones tributarias reales.
             */
            disclaimer: string;
            /** Retiros Pesos */
            retiros_pesos: string;
            /** Rli */
            rli: string;
            /** Scenarios */
            scenarios: components["schemas"]["RegimenScenario"][];
            /** Tax Year */
            tax_year: number;
        };
        /** CompareRequest */
        CompareRequest: {
            /** Ids */
            ids: string[];
        };
        /** CompareResponse */
        CompareResponse: {
            /**
             * Disclaimer
             * @default Disclaimer pendiente de carga desde privacy.legal_texts.
             */
            disclaimer: string;
            /** Plan Accion */
            plan_accion: components["schemas"]["PlanAccionItem"][];
            /** Scenarios */
            scenarios: components["schemas"]["CompareScenarioCard"][];
        };
        /** CompareScenarioCard */
        CompareScenarioCard: {
            /** Ahorro Total */
            ahorro_total: string;
            /** Banderas */
            banderas: components["schemas"]["BanderaRoja"][];
            base: components["schemas"]["ScenarioResultado"];
            /** Es Recomendado */
            es_recomendado: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Palancas Aplicadas */
            palancas_aplicadas: components["schemas"]["PalancaImpacto"][];
            /**
             * Regimen
             * @enum {string}
             */
            regimen: "14_a" | "14_d_3" | "14_d_8";
            simulado: components["schemas"]["ScenarioResultado"];
            /** Tax Year */
            tax_year: number;
        };
        /** CreateArcopRequest */
        CreateArcopRequest: {
            /**
             * Descripcion
             * @description Detalle libre del titular. Para 'rectificacion' incluir qué dato corregir y el valor solicitado.
             */
            descripcion?: string | null;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "acceso" | "rectificacion" | "cancelacion" | "oposicion" | "portabilidad";
        };
        /** CreateDraftRequest */
        CreateDraftRequest: {
            /** Domain */
            domain: string;
            /** Fuente Legal */
            fuente_legal: {
                [key: string]: unknown;
            }[];
            /** Key */
            key: string;
            /** Rules */
            rules: {
                [key: string]: unknown;
            };
            /**
             * Vigencia Desde
             * Format: date
             */
            vigencia_desde: string;
            /** Vigencia Hasta */
            vigencia_hasta?: string | null;
        };
        /** CreateEmpresaRequest */
        CreateEmpresaRequest: {
            /** Capital Inicial Uf */
            capital_inicial_uf?: number | string | null;
            /** Fecha Inicio Actividades */
            fecha_inicio_actividades?: string | null;
            /** Giro */
            giro?: string | null;
            /** Razon Social */
            razon_social: string;
            /**
             * Regimen Actual
             * @default desconocido
             * @enum {string}
             */
            regimen_actual: "14_a" | "14_d_3" | "14_d_8" | "presunta" | "desconocido";
            /** Rut */
            rut: string;
        };
        /** CreateWorkspaceReq */
        CreateWorkspaceReq: {
            /**
             * Consent Tratamiento Datos
             * @description Consentimiento explícito al tratamiento de datos personales y tributarios bajo Ley 19.628 + Ley 21.719. Versión consentimiento-tratamiento-datos-v1.
             * @constant
             */
            consent_tratamiento_datos: true;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "pyme" | "accounting_firm";
        };
        /** CreateWorkspaceResp */
        CreateWorkspaceResp: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "cfo" | "accountant_lead" | "accountant_staff" | "viewer";
            /**
             * Type
             * @enum {string}
             */
            type: "pyme" | "accounting_firm";
        };
        /**
         * DiagnoseRequest
         * @description Inputs del wizard de diagnóstico (skill 7, preguntas 4-12).
         */
        DiagnoseRequest: {
            /** Capital Efectivo Inicial Uf */
            capital_efectivo_inicial_uf: number | string;
            /**
             * Empresa Id
             * @description Empresa del workspace activo a la que se asocia el diagnóstico. Si se omite, queda como recomendación workspace-level.
             */
            empresa_id?: string | null;
            /** Ingresos Max Anual Uf */
            ingresos_max_anual_uf: number | string;
            /** Ingresos Promedio 3A Uf */
            ingresos_promedio_3a_uf: number | string;
            /** Participacion Empresas No 14D Sobre 10Pct */
            participacion_empresas_no_14d_sobre_10pct: boolean;
            /** Pct Ingresos Pasivos */
            pct_ingresos_pasivos: number | string;
            /**
             * Plan Retiros Pct
             * @description % de RLI que el dueño planea retirar cada año.
             */
            plan_retiros_pct: number | string;
            /**
             * Regimen Actual
             * @description Régimen vigente del contribuyente. Si se omite asume 14 A (supletorio).
             */
            regimen_actual?: ("14_a" | "14_d_3" | "14_d_8") | null;
            /**
             * Rli Proyectada Anual Uf
             * @description RLI esperada para cada uno de los próximos 3 años.
             */
            rli_proyectada_anual_uf: number | string;
            /**
             * Sector
             * @enum {string}
             */
            sector: "comercio" | "servicios" | "agricola" | "transporte" | "mineria" | "otro";
            /** Tax Year */
            tax_year: number;
            /** Todos Duenos Personas Naturales Chile */
            todos_duenos_personas_naturales_chile: boolean;
            /**
             * Ventas Anuales Uf
             * @description Ventas anuales actuales (UF). Se usa para evaluar renta presunta cuando el sector lo permite.
             */
            ventas_anuales_uf: number | string;
        };
        /** DiagnoseResponse */
        DiagnoseResponse: {
            /**
             * Disclaimer
             * @default Disclaimer pendiente de carga desde privacy.legal_texts.
             */
            disclaimer: string;
            /**
             * Disclaimer Version
             * @default v1
             */
            disclaimer_version: string;
            /** Elegibilidad */
            elegibilidad: components["schemas"]["EligibilityOut"][];
            /**
             * Engine Version
             * @default track-7b-mvp-001
             */
            engine_version: string;
            /** Fuente Legal */
            fuente_legal: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            proyeccion_dual_14d3: components["schemas"]["DualProjection"] | null;
            /** Proyecciones */
            proyecciones: components["schemas"]["RegimeProjection"][];
            /** Riesgos */
            riesgos: string[];
            /** Tax Year */
            tax_year: number;
            veredicto: components["schemas"]["DiagnoseVeredicto"];
        };
        /** DiagnoseVeredicto */
        DiagnoseVeredicto: {
            /** Ahorro 3A Clp */
            ahorro_3a_clp: string;
            /** Ahorro 3A Uf */
            ahorro_3a_uf: string;
            /**
             * Regimen Actual
             * @enum {string}
             */
            regimen_actual: "14_a" | "14_d_3" | "14_d_8";
            /**
             * Regimen Recomendado
             * @enum {string}
             */
            regimen_recomendado: "14_a" | "14_d_3" | "14_d_8" | "renta_presunta";
        };
        /** DryRunResponse */
        DryRunResponse: {
            /** Cambian Elegibilidad */
            cambian_elegibilidad: number;
            /** Delta Ahorro Total Clp */
            delta_ahorro_total_clp: string;
            /** Domain */
            domain: string;
            /** Evaluadas */
            evaluadas: number;
            /** Key */
            key: string;
            /** Nota */
            nota: string;
            /** Pasaban Antes */
            pasaban_antes: number;
            /** Pasan Ahora */
            pasan_ahora: number;
            /**
             * Rule Id
             * Format: uuid
             */
            rule_id: string;
        };
        /** DualProjection */
        DualProjection: {
            base: components["schemas"]["RegimeProjection"];
            revertido: components["schemas"]["RegimeProjection"];
        };
        /** EligibilityOut */
        EligibilityOut: {
            /** Elegible */
            elegible: boolean;
            /** Label */
            label: string;
            /**
             * Regimen
             * @enum {string}
             */
            regimen: "14_a" | "14_d_3" | "14_d_8" | "renta_presunta";
            /** Requisitos */
            requisitos: components["schemas"]["RequisitoOut"][];
        };
        /** EmpresaResponse */
        EmpresaResponse: {
            /** Capital Inicial Uf */
            capital_inicial_uf: string | null;
            /** Created At */
            created_at: string;
            /** Fecha Inicio Actividades */
            fecha_inicio_actividades: string | null;
            /** Giro */
            giro: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Razon Social */
            razon_social: string;
            /**
             * Regimen Actual
             * @enum {string}
             */
            regimen_actual: "14_a" | "14_d_3" | "14_d_8" | "presunta" | "desconocido";
            /** Rut */
            rut: string;
        };
        /** EmpresasListResponse */
        EmpresasListResponse: {
            /** Empresas */
            empresas: components["schemas"]["EmpresaResponse"][];
        };
        /** EvaluateAlertasRequest */
        EvaluateAlertasRequest: {
            /**
             * Empresa Id
             * Format: uuid
             */
            empresa_id: string;
            /** Palancas Aplicadas */
            palancas_aplicadas?: string[];
            /**
             * Regimen
             * @enum {string}
             */
            regimen: "14_a" | "14_d_3" | "14_d_8";
            /**
             * Retiros Declarados Pesos
             * @default 0
             */
            retiros_declarados_pesos: number | string;
            /** Rli Proyectada Pesos */
            rli_proyectada_pesos: number | string;
            /** Tax Year */
            tax_year: number;
        };
        /** EvaluateAlertasResponse */
        EvaluateAlertasResponse: {
            /** Alertas */
            alertas: components["schemas"]["AlertaResponse"][];
            /** Creadas */
            creadas: number;
            /** Ya Existentes */
            ya_existentes: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IdpcRequest */
        IdpcRequest: {
            /**
             * Regimen
             * @enum {string}
             */
            regimen: "14_a" | "14_d_3" | "14_d_8";
            /**
             * Rli
             * @description Renta Líquida Imponible en CLP
             */
            rli: number | string;
            /** Tax Year */
            tax_year: number;
        };
        /** IgcRequest */
        IgcRequest: {
            /**
             * Base Pesos
             * @description Base afecta a IGC del dueño en CLP
             */
            base_pesos: number | string;
            /** Tax Year */
            tax_year: number;
        };
        /** LegalTextResponse */
        LegalTextResponse: {
            /** Body */
            body: string;
            /** Effective From */
            effective_from: string;
            /** Key */
            key: string;
            /** Version */
            version: string;
        };
        /** MeResponse */
        MeResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            workspace: components["schemas"]["MeWorkspace"] | null;
        };
        /** MeWorkspace */
        MeWorkspace: {
            /** Empresa Ids */
            empresa_ids: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "cfo" | "accountant_lead" | "accountant_staff" | "viewer";
            /**
             * Type
             * @enum {string}
             */
            type: "pyme" | "accounting_firm";
        };
        /** PalancaImpacto */
        PalancaImpacto: {
            /** Aplicada */
            aplicada: boolean;
            /** Fuente Legal */
            fuente_legal: string;
            /** Label */
            label: string;
            /** Monto Aplicado */
            monto_aplicado: string;
            /** Nota */
            nota?: string | null;
            /** Palanca Id */
            palanca_id: string;
        };
        /**
         * Palancas
         * @description Subconjunto de palancas activas. Todas opcionales.
         */
        Palancas: {
            /**
             * Apv Monto
             * @description P9 — Aporte APV anual del dueño en CLP. Reduce la base imponible del IGC dentro del tope anual.
             */
            apv_monto?: number | string | null;
            /**
             * Credito Id Monto
             * @description P6 — Desembolso I+D certificado por CORFO en CLP. 35% se imputa como crédito IDPC (tope 15.000 UTM); 65% se reconoce como gasto deducible RLI.
             */
            credito_id_monto?: number | string | null;
            /**
             * Dep Instantanea
             * @description P1 — Monto del activo fijo a depreciar 100% en CLP.
             */
            dep_instantanea?: number | string | null;
            /**
             * Rebaja 14E Pct
             * @description P3 — Porcentaje (0-0,5) de RLI a reinvertir bajo art. 14 E. Se aplica el menor entre pct*RLI y el tope absoluto 5.000 UF.
             */
            rebaja_14e_pct?: number | string | null;
            /**
             * Retiros Adicionales
             * @description P4 — Retiros adicionales del dueño antes del 31-dic.
             */
            retiros_adicionales?: number | string | null;
            /**
             * Sence Monto
             * @description P2 — Gasto en capacitación SENCE en CLP. Genera crédito directo contra IDPC dentro del tope max(1% planilla, 9 UTM).
             */
            sence_monto?: number | string | null;
            /**
             * Sueldo Empresarial Mensual
             * @description P5 — Sueldo mensual al socio activo en CLP. Anualiza por 12 meses como gasto aceptado.
             */
            sueldo_empresarial_mensual?: number | string | null;
        };
        /** PlanAccionItem */
        PlanAccionItem: {
            /** Accion */
            accion: string;
            /**
             * Fecha Limite
             * @default 31-dic
             */
            fecha_limite: string;
            /** Fundamento Legal */
            fundamento_legal: string;
            /** Label */
            label: string;
            /** Palanca Id */
            palanca_id: string;
        };
        /** PpmRequest */
        PpmRequest: {
            /** Ingresos Anio Anterior Uf */
            ingresos_anio_anterior_uf: number | string;
            /** Ingresos Mes Pesos */
            ingresos_mes_pesos: number | string;
            /**
             * Regimen
             * @enum {string}
             */
            regimen: "14_d_3" | "14_d_8";
            /** Tax Year */
            tax_year: number;
        };
        /** ProjectionRow */
        ProjectionRow: {
            /** Año */
            "a\u00F1o": number;
            /** Carga Total */
            carga_total: string;
            /** Idpc */
            idpc: string;
            /** Igc Dueno */
            igc_dueno: string;
            /** Retiros */
            retiros: string;
            /** Rli */
            rli: string;
        };
        /**
         * RecomendacionListItem
         * @description Resumen de una recomendación persistida (skill 7b).
         */
        RecomendacionListItem: {
            /** Ahorro Estimado Clp */
            ahorro_estimado_clp: string | null;
            /** Created At */
            created_at: string;
            /** Descripcion */
            descripcion: string;
            /** Disclaimer Version */
            disclaimer_version: string;
            /** Empresa Id */
            empresa_id: string | null;
            /** Engine Version */
            engine_version: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Regimen Actual
             * @enum {string}
             */
            regimen_actual: "14_a" | "14_d_3" | "14_d_8";
            /**
             * Regimen Recomendado
             * @enum {string}
             */
            regimen_recomendado: "14_a" | "14_d_3" | "14_d_8" | "renta_presunta";
            /** Tax Year */
            tax_year: number;
            /** Tipo */
            tipo: string;
        };
        /** RecomendacionListResponse */
        RecomendacionListResponse: {
            /** Recomendaciones */
            recomendaciones: components["schemas"]["RecomendacionListItem"][];
        };
        /** RegimeProjection */
        RegimeProjection: {
            /**
             * Es Transitoria
             * @default false
             */
            es_transitoria: boolean;
            /** Label */
            label: string;
            /** Nota */
            nota?: string | null;
            /**
             * Regimen
             * @enum {string}
             */
            regimen: "14_a" | "14_d_3" | "14_d_8" | "renta_presunta";
            /** Rows */
            rows: components["schemas"]["ProjectionRow"][];
            /** Total 3A */
            total_3a: string;
        };
        /** RegimenScenario */
        RegimenScenario: {
            /** Ahorro Vs 14A */
            ahorro_vs_14a: string;
            /** Carga Total */
            carga_total: string;
            /** Es Recomendado */
            es_recomendado: boolean;
            /** Es Transitoria */
            es_transitoria: boolean;
            /** Fuente Legal */
            fuente_legal: string;
            /** Idpc */
            idpc: string;
            /** Igc Dueno */
            igc_dueno: string;
            /** Label */
            label: string;
            /** Nota */
            nota: string | null;
            /**
             * Regimen
             * @enum {string}
             */
            regimen: "14_a" | "14_d_3" | "14_d_3_revertido" | "14_d_8";
        };
        /** RequisitoOut */
        RequisitoOut: {
            /** Fundamento */
            fundamento: string;
            /** Ok */
            ok: boolean;
            /** Texto */
            texto: string;
        };
        /** RuleSetDetail */
        RuleSetDetail: {
            /** Created At */
            created_at: string;
            /** Domain */
            domain: string;
            /** Fuente Legal */
            fuente_legal: {
                [key: string]: unknown;
            }[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Published At */
            published_at: string | null;
            /** Published By Admin */
            published_by_admin: string | null;
            /** Published By Contador */
            published_by_contador: string | null;
            /** Rules */
            rules: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Version */
            version: number;
            /** Vigencia Desde */
            vigencia_desde: string;
            /** Vigencia Hasta */
            vigencia_hasta: string | null;
        };
        /** RuleSetListResponse */
        RuleSetListResponse: {
            /** Rule Sets */
            rule_sets: components["schemas"]["RuleSetSummary"][];
        };
        /** RuleSetSummary */
        RuleSetSummary: {
            /** Created At */
            created_at: string;
            /** Domain */
            domain: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Published At */
            published_at: string | null;
            /** Published By Admin */
            published_by_admin: string | null;
            /** Published By Contador */
            published_by_contador: string | null;
            /** Status */
            status: string;
            /** Version */
            version: number;
            /** Vigencia Desde */
            vigencia_desde: string;
            /** Vigencia Hasta */
            vigencia_hasta: string | null;
        };
        /** ScenarioListItem */
        ScenarioListItem: {
            /** Ahorro Total */
            ahorro_total: string;
            /** Carga Base */
            carga_base: string;
            /** Carga Simulada */
            carga_simulada: string;
            /** Created At */
            created_at: string;
            /** Empresa Id */
            empresa_id: string | null;
            /** Es Recomendado */
            es_recomendado: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /**
             * Regimen
             * @enum {string}
             */
            regimen: "14_a" | "14_d_3" | "14_d_8";
            /** Tax Year */
            tax_year: number;
        };
        /** ScenarioListResponse */
        ScenarioListResponse: {
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioListItem"][];
        };
        /** ScenarioRequest */
        ScenarioRequest: {
            /**
             * Empresa Id
             * @description Empresa del workspace activo a la que se asocia el escenario. Si se omite, queda como escenario workspace-level.
             */
            empresa_id?: string | null;
            /**
             * Nombre
             * @description Nombre opcional del escenario (ej. 'Sin palancas', 'Plan A'). Si se omite, se autogenera con régimen + año + timestamp.
             */
            nombre?: string | null;
            palancas?: components["schemas"]["Palancas"];
            /**
             * Planilla Anual Pesos
             * @description Planilla anual de remuneraciones imponibles en CLP. Sirve para calcular el tope SENCE (max 1% planilla, mínimo 9 UTM).
             * @default 0
             */
            planilla_anual_pesos: number | string;
            /**
             * Regimen
             * @enum {string}
             */
            regimen: "14_a" | "14_d_3" | "14_d_8";
            /**
             * Retiros Base
             * @description Retiros del dueño ya realizados en el año.
             * @default 0
             */
            retiros_base: number | string;
            /**
             * Rli Base
             * @description RLI proyectada del año.
             */
            rli_base: number | string;
            /** Tax Year */
            tax_year: number;
        };
        /** ScenarioResponse */
        ScenarioResponse: {
            /** Ahorro Total */
            ahorro_total: string;
            /** Banderas */
            banderas: components["schemas"]["BanderaRoja"][];
            base: components["schemas"]["ScenarioResultado"];
            /**
             * Disclaimer
             * @default Disclaimer pendiente de carga desde privacy.legal_texts.
             */
            disclaimer: string;
            /**
             * Engine Version
             * @default track-8b-mvp-001
             */
            engine_version: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Palancas Aplicadas */
            palancas_aplicadas: components["schemas"]["PalancaImpacto"][];
            /**
             * Regimen
             * @enum {string}
             */
            regimen: "14_a" | "14_d_3" | "14_d_8";
            simulado: components["schemas"]["ScenarioResultado"];
            /** Tax Year */
            tax_year: number;
        };
        /** ScenarioResultado */
        ScenarioResultado: {
            /** Carga Total */
            carga_total: string;
            /** Idpc */
            idpc: string;
            /** Igc Dueno */
            igc_dueno: string;
            /** Retiros Total */
            retiros_total: string;
            /** Rli */
            rli: string;
        };
        /** UltimaRecomendacion */
        UltimaRecomendacion: {
            /** Ahorro Estimado Clp */
            ahorro_estimado_clp: string | null;
            /** Created At */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Regimen Recomendado */
            regimen_recomendado: string;
        };
        /** UltimaSimulacion */
        UltimaSimulacion: {
            /** Ahorro Total Clp */
            ahorro_total_clp: string;
            /** Created At */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** UpdateAlertaRequest */
        UpdateAlertaRequest: {
            /**
             * Estado
             * @enum {string}
             */
            estado: "nueva" | "vista" | "descartada" | "accionada";
        };
        /**
         * UpdateArcopRequest
         * @description PATCH del DPO (skill 5b). Cambia estado y/o registra respuesta.
         */
        UpdateArcopRequest: {
            /** Estado */
            estado?: ("recibida" | "en_proceso" | "cumplida" | "rechazada") | null;
            /** Respuesta */
            respuesta?: string | null;
        };
        /** ValidateSchemaRequest */
        ValidateSchemaRequest: {
            /** Domain */
            domain: string;
            /** Rules */
            rules: {
                [key: string]: unknown;
            };
        };
        /** ValidateSchemaResponse */
        ValidateSchemaResponse: {
            /** Domains Disponibles */
            domains_disponibles: string[];
            /** Errors */
            errors: components["schemas"]["ValidationFailureOut"][];
            /** Valid */
            valid: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationFailureOut */
        ValidationFailureOut: {
            /** Message */
            message: string;
            /** Path */
            path: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_rules_api_admin_rules_get: {
        parameters: {
            query?: {
                status_filter?: string | null;
                domain?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_draft_api_admin_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_schema_api_admin_rules_validate_schema_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateSchemaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateSchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rule_api_admin_rules__rule_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deprecate_rule_api_admin_rules__rule_id__deprecate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSetSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dry_run_api_admin_rules__rule_id__dry_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_rule_api_admin_rules__rule_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSetSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_contador_api_admin_rules__rule_id__sign_contador_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSetSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alertas_api_alertas_get: {
        parameters: {
            query?: {
                empresa_id?: string | null;
                incluir_cerradas?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertasListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_alertas_api_alertas_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateAlertasRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluateAlertasResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_alerta_api_alertas__alerta_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alerta_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAlertaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    comparador_regimen_api_calc_comparador_regimen_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparadorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparadorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calc_idpc_api_calc_idpc_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdpcRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calc_igc_api_calc_igc_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IgcRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calc_ppm_api_calc_ppm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PpmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cartera_api_cartera_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarteraResponse"];
                };
            };
        };
    };
    list_empresas_api_empresas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresasListResponse"];
                };
            };
        };
    };
    create_empresa_api_empresas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmpresaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_legal_api_legal__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalTextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_arcop_api_privacy_arcop_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArcopListResponse"];
                };
            };
        };
    };
    create_arcop_api_privacy_arcop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateArcopRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArcopResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_arcop_api_privacy_arcop__arcop_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arcop_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateArcopRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArcopResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_legal_public_api_public_legal__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalTextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnose_api_regime_diagnose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnoseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnoseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recomendaciones_api_regime_recomendaciones_get: {
        parameters: {
            query?: {
                tax_year?: number | null;
                empresa_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecomendacionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_scenario_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_scenario_list_get: {
        parameters: {
            query?: {
                tax_year?: number | null;
                empresa_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_api_scenario_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workspace_api_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateWorkspaceResp"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
